CRITICAL - 2022-04-24 17:14:20 --> unlink(C:\xampp\htdocs\Mendez\writable\debugbar/debugbar_1650499109.json): No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'unlink(C:\\xampp...', 'C:\\xampp\\htdocs...', 74, Array)
#1 C:\xampp\htdocs\Mendez\system\Debug\Toolbar\Collectors\History.php(74): unlink('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\Mendez\system\Debug\Toolbar.php(487): CodeIgniter\Debug\Toolbar\Collectors\History->setFiles(1650838460, 20)
#3 C:\xampp\htdocs\Mendez\system\Debug\Toolbar.php(464): CodeIgniter\Debug\Toolbar->format(Array, 'html')
#4 C:\xampp\htdocs\Mendez\app\Config\Events.php(48): CodeIgniter\Debug\Toolbar->respond()
#5 C:\xampp\htdocs\Mendez\system\Events\Events.php(149): CodeIgniter\Events\Events::Config\{closure}()
#6 C:\xampp\htdocs\Mendez\system\CodeIgniter.php(308): CodeIgniter\Events\Events::trigger('pre_system')
#7 C:\xampp\htdocs\Mendez\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-04-24 18:31:56 --> file_get_contents(): read of 8192 bytes failed with errno=13 Permission denied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(8, 'file_get_conten...', 'C:\\xampp\\htdocs...', 464, Array)
#1 C:\xampp\htdocs\Mendez\system\Debug\Toolbar.php(464): file_get_contents('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\Mendez\app\Config\Events.php(48): CodeIgniter\Debug\Toolbar->respond()
#3 C:\xampp\htdocs\Mendez\system\Events\Events.php(149): CodeIgniter\Events\Events::Config\{closure}()
#4 C:\xampp\htdocs\Mendez\system\CodeIgniter.php(308): CodeIgniter\Events\Events::trigger('pre_system')
#5 C:\xampp\htdocs\Mendez\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
